apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      apps: llm-inference
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http