apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1 # default replica count
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: myapp
  type:  LoadBalancer
  ports:
  - name: nginx-port
    port:  80
    targetPort:  80